### PR TITLE
Support for Preview .NET 7.200 SDK

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by yowl** [comment]
This is interesting.  `EmitLegacyAssetsFileItems` looks like something to bring in asset files, what is the error without this option?

**Comment by kant2002** [comment]
```
...\microsoft.dotnet.ilcompiler.llvm\7.0.0-preview.4.23073.1\build\Microsoft.DotNet.ILCompiler.targets(55,5): error : The PackageDefinitions ItemGroup is required for target ImportRuntimeIlcPackageTarget [NativeAOTWasm.csproj]
```

If you open `Microsoft.PackageDependencyResolution.targets` approximately from `C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets`
in the target `RunResolvePackageDependencies` you will have
```
<ResolvePackageDependencies
      ProjectPath="$(MSBuildProjectFullPath)"
      ProjectAssetsFile="$(ProjectAssetsFile)"
      ProjectLanguage="$(Language)"
      TargetFramework="$(TargetFramework)"
      ContinueOnError="ErrorAndContinue">
```
but in preview 
```
<ResolvePackageDependencies
      ProjectPath="$(MSBuildProjectFullPath)"
      ProjectAssetsFile="$(ProjectAssetsFile)"
      ProjectLanguage="$(Language)"
      TargetFramework="$(TargetFramework)"
      ContinueOnError="ErrorAndContinue"
      Condition="'$(EmitLegacyAssetsFileItems)' == 'true'">
```

**Comment by yowl** [comment]
Thanks, I suppose when we merge more upstream into NativeAot-LLVM, this will go away.  Thanks.

**Review by yowl — APPROVED** [review]
Thanks

**Comment by kant2002** [comment]
I just try to make this sample to work as smooth as butter

**Pull request merged**
